export const API_ENDPOINTS = {
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  CATEGORIES: "/categories",
  FEATURED_CATEGORIES: "/featured_categories",
  COLLECTIONS: "/collections",
  BRANDS: "/brands",
  PRODUCTS: "/products",
  COLOR: "/color",
  FEATURED_PRODUCTS: "/category/featured-products",
  TOP_SELLER_PRODUCTS: "/products_top_seller",
  ON_SELLING_PRODUCTS: "/category/on-selling",
  PRODUCT: `/product`,
  BEST_SELLER_PRODUCTS: "/products_best_seller",
  NEW_ARRIVAL_PRODUCTS: "/category/new-arrival",
  FLASH_SALE_PRODUCTS: "/category/flash-sale",
  SEARCH: "/search",
  ORDERS: "/orders",
  ORDER: "/order",
  VERIFY_COUPON_CODE: "verify_coupon_code",
  DIVISION: "/division",
  MY_ORDERS: "/my_orders",
  MY_REFERRAL_CODE: "/my_referral_code",
  USER_CHECK: "/user_check",
  MY_COUPONS: "/my_coupons",
  PRE_LOVED: "/pre_loved",
  MY_PRE_LOVED: "/my_pre_loved",

  // Otp related endpoints
  REQUEST_OTP: "/requestOtp",
};
